;; some keybindings I like
(global-set-key [f1]      'goto-line)  
(global-set-key [f2]      'longlines-mode)
(global-set-key [f5]      'menu-bar-mode)
(global-set-key [f8]      'flymake-mode)
(global-set-key [f9]      'python-mode)
(global-set-key "\C-cvg"  'goto-line)  
(global-set-key "\C-cvl" 'longlines-mode)
(global-set-key "\C-cvm"  'menu-bar-mode)
(global-set-key "\C-cvf"  'flymake-mode)
(global-set-key "\C-cvp"  'python-mode)
(require 'doctest-mode)
(global-set-key [f10]      'doctest-mode)
(global-set-key "\C-cvd"  'doctest-mode)
(global-set-key [f11]      'rst-mode)
(global-set-key "\C-cvr"  'rst-mode)
(global-set-key "\C-cva"  'beginning-of-line-text)
