#!/usr/bin/env python
# -*- coding: utf-8 -*-
# --
# contributor : Matthew Brett
# name : Python file template .... :

__author__ = "Matthew Brett (matthew.brett@gmail.com)"
__date__   = "`(current-time-string)`"


